#ifndef QTARDUINOCONTROLLERLIB_GLOBAL_H
#define QTARDUINOCONTROLLERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTARDUINOCONTROLLERLIB_LIBRARY)
#  define QTARDUINOCONTROLLERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTARDUINOCONTROLLERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTARDUINOCONTROLLERLIB_GLOBAL_H
